import type { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  // ACCESSORIES
  {
    id: "acc-001",
    name: "Aviator Frames — Gold",
    category: "accessories",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&q=80",
    overlayUrl: "/overlays/aviator-gold.png",
    anchor: "eyes",
    faceShapes: ["square", "heart", "oval"],
    seasonalTones: ["autumn", "spring"],
    description: "Lightweight teardrop aviators with a warm gold finish.",
    inStock: true,
  },
  {
    id: "acc-002",
    name: "Rounded Acetate — Tortoise",
    category: "accessories",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&q=80",
    overlayUrl: "/overlays/round-tortoise.png",
    anchor: "eyes",
    faceShapes: ["square", "oblong", "diamond"],
    seasonalTones: ["autumn", "winter"],
    description: "Soft round acetate frames that offset angular jawlines.",
    inStock: true,
  },
  {
    id: "acc-003",
    name: "Wayfarer — Matte Black",
    category: "accessories",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1508296695146-257a814070b4?w=400&q=80",
    overlayUrl: "/overlays/wayfarer-black.png",
    anchor: "eyes",
    faceShapes: ["round", "oval", "heart"],
    seasonalTones: ["winter", "summer"],
    description: "Bold squared frames that add structure to softer faces.",
    inStock: true,
  },
  {
    id: "acc-004",
    name: "Felt Fedora — Camel",
    category: "accessories",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?w=400&q=80",
    overlayUrl: "/overlays/fedora-camel.png",
    anchor: "forehead",
    faceShapes: ["oval", "round", "heart"],
    seasonalTones: ["autumn", "spring"],
    description: "Wide-brim camel fedora that elongates rounder faces.",
    inStock: true,
  },
  {
    id: "acc-005",
    name: "Cat-Eye — Rose Gold",
    category: "accessories",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&q=80",
    overlayUrl: "/overlays/aviator-gold.png",
    anchor: "eyes",
    faceShapes: ["oval", "round", "heart"],
    seasonalTones: ["spring", "summer"],
    description: "Elegant cat-eye frames with a rose gold finish.",
    inStock: true,
  },
  {
    id: "acc-006",
    name: "Baseball Cap — Navy",
    category: "accessories",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400&q=80",
    overlayUrl: "/overlays/fedora-camel.png",
    anchor: "forehead",
    faceShapes: ["oval", "square", "diamond"],
    seasonalTones: ["summer", "spring"],
    description: "Classic navy cap for a casual everyday look.",
    inStock: true,
  },
  // CLOTHES
  {
    id: "clo-001",
    name: "Linen Shirt — Sage",
    category: "clothes",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval", "oblong", "diamond"],
    seasonalTones: ["spring", "summer"],
    description: "Breathable sage linen — flatters cool, muted complexions.",
    inStock: true,
  },
  {
    id: "clo-002",
    name: "Merino Crew — Charcoal",
    category: "clothes",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1516826957135-700dedea698c?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["round", "heart", "square"],
    seasonalTones: ["winter", "summer"],
    description: "Deep charcoal merino with high contrast for winter tones.",
    inStock: true,
  },
  {
    id: "clo-003",
    name: "Oxford Shirt — Rust",
    category: "clothes",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["square", "oval"],
    seasonalTones: ["autumn"],
    description: "Earthy rust oxford that warms autumn complexions.",
    inStock: true,
  },
  {
    id: "clo-004",
    name: "Floral Kurta — Ivory",
    category: "clothes",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval", "round", "heart"],
    seasonalTones: ["spring", "summer"],
    description: "Elegant ivory kurta with subtle floral embroidery.",
    inStock: true,
  },
  {
    id: "clo-005",
    name: "Denim Jacket — Indigo",
    category: "clothes",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval", "square", "diamond"],
    seasonalTones: ["winter", "autumn"],
    description: "Classic indigo denim jacket for all face shapes.",
    inStock: true,
  },
  {
    id: "clo-006",
    name: "Blazer — Camel",
    category: "clothes",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval", "oblong", "heart"],
    seasonalTones: ["autumn", "spring"],
    description: "Structured camel blazer for warm seasonal tones.",
    inStock: true,
  },
  // SKINCARE
  {
    id: "skn-001",
    name: "Hydrating SPF 50",
    category: "skincare",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval","round","square","heart","oblong","diamond"],
    seasonalTones: ["spring","summer","autumn","winter"],
    description: "Lightweight broad-spectrum SPF, no white cast on deeper tones.",
    inStock: true,
  },
  {
    id: "skn-002",
    name: "Warm-Tone Tinted Balm",
    category: "skincare",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval","round","square","heart","oblong","diamond"],
    seasonalTones: ["autumn", "spring"],
    description: "Sheer balm tuned for warm undertones and golden skin.",
    inStock: true,
  },
  {
    id: "skn-003",
    name: "Cool-Tone Brightening Serum",
    category: "skincare",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval","round","square","heart","oblong","diamond"],
    seasonalTones: ["summer", "winter"],
    description: "Vitamin-C serum that evens cool, pink-based complexions.",
    inStock: true,
  },
  {
    id: "skn-004",
    name: "Niacinamide Face Wash",
    category: "skincare",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval","round","square","heart","oblong","diamond"],
    seasonalTones: ["spring","summer","autumn","winter"],
    description: "Gentle niacinamide cleanser for all skin tones.",
    inStock: true,
  },
  {
    id: "skn-005",
    name: "Rose Hip Face Oil",
    category: "skincare",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval","round","square","heart","oblong","diamond"],
    seasonalTones: ["autumn","winter"],
    description: "Nourishing rose hip oil for dry and mature skin tones.",
    inStock: true,
  },
  {
    id: "skn-006",
    name: "Aloe Vera Gel Moisturiser",
    category: "skincare",
    price: 0,
    currency: "INR",
    imageUrl: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400&q=80",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval","round","square","heart","oblong","diamond"],
    seasonalTones: ["spring","summer"],
    description: "Light aloe gel perfect for oily and combination skin.",
    inStock: true,
  },
];
