// ============================================================================
// lib/products/mockData.ts — Seed catalog (also the Supabase seed source)
// ============================================================================
import type { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  // ---------------- ACCESSORIES (AR-wearable) ----------------
  {
    id: "acc-001",
    name: "Aviator Frames — Gold",
    category: "accessories",
    price: 2499,
    currency: "INR",
    imageUrl: "/products/aviator-gold.png",
    overlayUrl: "/overlays/aviator-gold.png",
    anchor: "eyes",
    faceShapes: ["square", "heart", "oval"],
    seasonalTones: ["autumn", "spring"],
    description: "Lightweight teardrop aviators with a warm gold finish.",
    inStock: true,
  },
  {
    id: "acc-002",
    name: "Rounded Acetate — Tortoise",
    category: "accessories",
    price: 1899,
    currency: "INR",
    imageUrl: "/products/round-tortoise.png",
    overlayUrl: "/overlays/round-tortoise.png",
    anchor: "eyes",
    faceShapes: ["square", "oblong", "diamond"],
    seasonalTones: ["autumn", "winter"],
    description: "Soft round acetate frames that offset angular jawlines.",
    inStock: true,
  },
  {
    id: "acc-003",
    name: "Wayfarer — Matte Black",
    category: "accessories",
    price: 2199,
    currency: "INR",
    imageUrl: "/products/wayfarer-black.png",
    overlayUrl: "/overlays/wayfarer-black.png",
    anchor: "eyes",
    faceShapes: ["round", "oval", "heart"],
    seasonalTones: ["winter", "summer"],
    description: "Bold squared frames that add structure to softer faces.",
    inStock: true,
  },
  {
    id: "acc-004",
    name: "Felt Fedora — Camel",
    category: "accessories",
    price: 1599,
    currency: "INR",
    imageUrl: "/products/fedora-camel.png",
    overlayUrl: "/overlays/fedora-camel.png",
    anchor: "forehead",
    faceShapes: ["oval", "round", "heart"],
    seasonalTones: ["autumn", "spring"],
    description: "Wide-brim camel fedora that elongates rounder faces.",
    inStock: true,
  },
  // ---------------- CLOTHES ----------------
  {
    id: "clo-001",
    name: "Linen Shirt — Sage",
    category: "clothes",
    price: 1799,
    currency: "INR",
    imageUrl: "/products/linen-sage.png",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval", "oblong", "diamond"],
    seasonalTones: ["spring", "summer"],
    description: "Breathable sage linen — flatters cool, muted complexions.",
    inStock: true,
  },
  {
    id: "clo-002",
    name: "Merino Crew — Charcoal",
    category: "clothes",
    price: 2999,
    currency: "INR",
    imageUrl: "/products/merino-charcoal.png",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["round", "heart", "square"],
    seasonalTones: ["winter", "summer"],
    description: "Deep charcoal merino with high contrast for winter tones.",
    inStock: true,
  },
  {
    id: "clo-003",
    name: "Oxford Shirt — Rust",
    category: "clothes",
    price: 2199,
    currency: "INR",
    imageUrl: "/products/oxford-rust.png",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["square", "oval"],
    seasonalTones: ["autumn"],
    description: "Earthy rust oxford that warms autumn complexions.",
    inStock: false,
  },
  // ---------------- SKINCARE ----------------
  {
    id: "skn-001",
    name: "Hydrating SPF 50 — Universal",
    category: "skincare",
    price: 899,
    currency: "INR",
    imageUrl: "/products/spf50.png",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval", "round", "square", "heart", "oblong", "diamond"],
    seasonalTones: ["spring", "summer", "autumn", "winter"],
    description: "Lightweight broad-spectrum SPF, no white cast on deeper tones.",
    inStock: true,
  },
  {
    id: "skn-002",
    name: "Warm-Tone Tinted Balm",
    category: "skincare",
    price: 749,
    currency: "INR",
    imageUrl: "/products/tinted-warm.png",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval", "round", "square", "heart", "oblong", "diamond"],
    seasonalTones: ["autumn", "spring"],
    description: "Sheer balm tuned for warm undertones and golden skin.",
    inStock: true,
  },
  {
    id: "skn-003",
    name: "Cool-Tone Brightening Serum",
    category: "skincare",
    price: 1299,
    currency: "INR",
    imageUrl: "/products/serum-cool.png",
    overlayUrl: null,
    anchor: "none",
    faceShapes: ["oval", "round", "square", "heart", "oblong", "diamond"],
    seasonalTones: ["summer", "winter"],
    description: "Vitamin-C serum that evens cool, pink-based complexions.",
    inStock: true,
  },
];
